import Navbar from '@/components/Navbar'
import './globals.css'
import localFont from 'next/font/local'
import Footer from '@/components/footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const myFont = localFont({
  src: [
    {
      path: '../../public/gothampro_light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/gothampro.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/gothampro_medium.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/gothampro_bold.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}

